# 服務器端口
server:
  port: 8080

spring:
  application: # 應用名稱
    name: chatapp
  datasource:
    url: jdbc:h2:file:./data/chatdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2: # H2數據庫配置
    console:
      enable: true
      path: /h2-console
      settings: # 啟用H2控制台
        web-allow-others: false
  jpa: # JPA配置
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 自動建立資料夾
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:  # Thymeleaf配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  session: # Spring Session配置
    store-type: jdbc
    jdbc:
      initialize-schema: always
  servlet: # 檔案上傳配置
    session:
      timeout: 30m
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  file: # 檔案上傳配置
    upload-dir: uploads
  web: # 靜態資源處理
    resources:
      static-locations: classpath:/static/,file:./uploads/
logging: # 日誌配置
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
    com:
      example:
        chatapp: DEBUG